function createfigure2(X1, Y1, Y2, Y3)
%CREATEFIGURE2(X1, Y1, Y2, Y3)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 16-Jan-2016 17:58:33

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.709264705882353 0.775 0.215735294117647]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 412]);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Parent',axes1,'LineWidth',2);

% Create xlabel
xlabel('线路编号','FontWeight','bold','FontSize',14);

% Create ylabel
ylabel('网络平均效率','FontWeight','bold','FontSize',14);

% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.13 0.409632352941176 0.775 0.215735294117647]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0 412]);
box(axes2,'on');
hold(axes2,'all');

% Create plot
plot(X1,Y2,'Parent',axes2,...
    'MarkerFaceColor',[0.313725501298904 0.313725501298904 0.313725501298904],...
    'LineWidth',2,...
    'Color',[0.501960813999176 0.501960813999176 0.501960813999176]);

% Create xlabel
xlabel('线路编号','FontWeight','bold','FontSize',14);

% Create ylabel
ylabel('过载率(%)','FontWeight','bold','FontSize',14);

% Create axes
axes3 = axes('Parent',figure1,...
    'Position',[0.13 0.11 0.775 0.215735294117647]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes3,[0 412]);
box(axes3,'on');
hold(axes3,'all');

% Create plot
plot(X1,Y3,'Parent',axes3,'LineWidth',2,'Color',[1 0 0]);

% Create xlabel
xlabel('线路编号','FontWeight','bold','FontSize',14);

% Create ylabel
ylabel('电网传输能力','FontWeight','bold','FontSize',14);

